export default {
  CHROME: 'CHROME',
  FIREFOX: 'FIREFOX',
  DESKTOP_SAFARI: 'DESKTOP_SAFARI',
  IE: 'IE',
  MOBILE_SAFARI: 'MOBILE_SAFARI',
  MOBILE_IOS_CHROME: 'MOBILE_IOS_CHROME',
  ETC: 'ETC',
};
